// Code generated by protoc-gen-secv. DO NOT EDIT.
// source: longcom.proto

package svip_longcom

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = unicode.IsUpper
)

// Validate checks the field values on GetTokenRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetTokenRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTokenRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetTokenRequestMultiError, or nil if none found.
func (m *GetTokenRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTokenRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetAppName()) < 1 {
		err := GetTokenRequestValidationError{
			field:  "AppName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Topic

	if utf8.RuneCountInString(m.GetUserId()) < 5 {
		err := GetTokenRequestValidationError{
			field:  "UserId",
			reason: "value length must be at least 5 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for CallbackUrl

	if len(errors) > 0 {
		return GetTokenRequestMultiError(errors)
	}

	return nil
}

// GetTokenRequestMultiError is an error wrapping multiple validation errors
// returned by GetTokenRequest.ValidateAll() if the designated constraints
// aren't met.
type GetTokenRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTokenRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTokenRequestMultiError) AllErrors() []error { return m }

// GetTokenRequestValidationError is the validation error returned by
// GetTokenRequest.Validate if the designated constraints aren't met.
type GetTokenRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTokenRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTokenRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTokenRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTokenRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTokenRequestValidationError) ErrorName() string { return "GetTokenRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetTokenRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTokenRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTokenRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTokenRequestValidationError{}

// Validate checks the field values on GetTokenResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetTokenResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTokenResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetTokenResponseMultiError, or nil if none found.
func (m *GetTokenResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTokenResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Token

	if len(errors) > 0 {
		return GetTokenResponseMultiError(errors)
	}

	return nil
}

// GetTokenResponseMultiError is an error wrapping multiple validation errors
// returned by GetTokenResponse.ValidateAll() if the designated constraints
// aren't met.
type GetTokenResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTokenResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTokenResponseMultiError) AllErrors() []error { return m }

// GetTokenResponseValidationError is the validation error returned by
// GetTokenResponse.Validate if the designated constraints aren't met.
type GetTokenResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTokenResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTokenResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTokenResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTokenResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTokenResponseValidationError) ErrorName() string { return "GetTokenResponseValidationError" }

// Error satisfies the builtin error interface
func (e GetTokenResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTokenResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTokenResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTokenResponseValidationError{}

// Validate checks the field values on ConnectRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ConnectRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ConnectRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ConnectRequestMultiError,
// or nil if none found.
func (m *ConnectRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ConnectRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetToken()) < 6 {
		err := ConnectRequestValidationError{
			field:  "Token",
			reason: "value length must be at least 6 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ConnectRequestMultiError(errors)
	}

	return nil
}

// ConnectRequestMultiError is an error wrapping multiple validation errors
// returned by ConnectRequest.ValidateAll() if the designated constraints
// aren't met.
type ConnectRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ConnectRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ConnectRequestMultiError) AllErrors() []error { return m }

// ConnectRequestValidationError is the validation error returned by
// ConnectRequest.Validate if the designated constraints aren't met.
type ConnectRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConnectRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConnectRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConnectRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConnectRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConnectRequestValidationError) ErrorName() string { return "ConnectRequestValidationError" }

// Error satisfies the builtin error interface
func (e ConnectRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConnectRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConnectRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConnectRequestValidationError{}

// Validate checks the field values on ConnectResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ConnectResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ConnectResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ConnectResponseMultiError, or nil if none found.
func (m *ConnectResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ConnectResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ConnId

	if len(errors) > 0 {
		return ConnectResponseMultiError(errors)
	}

	return nil
}

// ConnectResponseMultiError is an error wrapping multiple validation errors
// returned by ConnectResponse.ValidateAll() if the designated constraints
// aren't met.
type ConnectResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ConnectResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ConnectResponseMultiError) AllErrors() []error { return m }

// ConnectResponseValidationError is the validation error returned by
// ConnectResponse.Validate if the designated constraints aren't met.
type ConnectResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConnectResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConnectResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConnectResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConnectResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConnectResponseValidationError) ErrorName() string { return "ConnectResponseValidationError" }

// Error satisfies the builtin error interface
func (e ConnectResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConnectResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConnectResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConnectResponseValidationError{}

// Validate checks the field values on SendMessageRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SendMessageRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendMessageRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SendMessageRequestMultiError, or nil if none found.
func (m *SendMessageRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SendMessageRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ConnId

	// no validation rules for Message

	if len(errors) > 0 {
		return SendMessageRequestMultiError(errors)
	}

	return nil
}

// SendMessageRequestMultiError is an error wrapping multiple validation errors
// returned by SendMessageRequest.ValidateAll() if the designated constraints
// aren't met.
type SendMessageRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendMessageRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendMessageRequestMultiError) AllErrors() []error { return m }

// SendMessageRequestValidationError is the validation error returned by
// SendMessageRequest.Validate if the designated constraints aren't met.
type SendMessageRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendMessageRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendMessageRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendMessageRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendMessageRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendMessageRequestValidationError) ErrorName() string {
	return "SendMessageRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SendMessageRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendMessageRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendMessageRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendMessageRequestValidationError{}

// Validate checks the field values on SendMessageResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SendMessageResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendMessageResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SendMessageResponseMultiError, or nil if none found.
func (m *SendMessageResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SendMessageResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return SendMessageResponseMultiError(errors)
	}

	return nil
}

// SendMessageResponseMultiError is an error wrapping multiple validation
// errors returned by SendMessageResponse.ValidateAll() if the designated
// constraints aren't met.
type SendMessageResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendMessageResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendMessageResponseMultiError) AllErrors() []error { return m }

// SendMessageResponseValidationError is the validation error returned by
// SendMessageResponse.Validate if the designated constraints aren't met.
type SendMessageResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendMessageResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendMessageResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendMessageResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendMessageResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendMessageResponseValidationError) ErrorName() string {
	return "SendMessageResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SendMessageResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendMessageResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendMessageResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendMessageResponseValidationError{}

// Validate checks the field values on SendMessageByUserRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SendMessageByUserRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendMessageByUserRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SendMessageByUserRequestMultiError, or nil if none found.
func (m *SendMessageByUserRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SendMessageByUserRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetAppName()) < 1 {
		err := SendMessageByUserRequestValidationError{
			field:  "AppName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Topic

	if utf8.RuneCountInString(m.GetUserId()) < 5 {
		err := SendMessageByUserRequestValidationError{
			field:  "UserId",
			reason: "value length must be at least 5 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Message

	if len(errors) > 0 {
		return SendMessageByUserRequestMultiError(errors)
	}

	return nil
}

// SendMessageByUserRequestMultiError is an error wrapping multiple validation
// errors returned by SendMessageByUserRequest.ValidateAll() if the designated
// constraints aren't met.
type SendMessageByUserRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendMessageByUserRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendMessageByUserRequestMultiError) AllErrors() []error { return m }

// SendMessageByUserRequestValidationError is the validation error returned by
// SendMessageByUserRequest.Validate if the designated constraints aren't met.
type SendMessageByUserRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendMessageByUserRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendMessageByUserRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendMessageByUserRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendMessageByUserRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendMessageByUserRequestValidationError) ErrorName() string {
	return "SendMessageByUserRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SendMessageByUserRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendMessageByUserRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendMessageByUserRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendMessageByUserRequestValidationError{}

// Validate checks the field values on SendMessageByUserResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SendMessageByUserResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendMessageByUserResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SendMessageByUserResponseMultiError, or nil if none found.
func (m *SendMessageByUserResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SendMessageByUserResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return SendMessageByUserResponseMultiError(errors)
	}

	return nil
}

// SendMessageByUserResponseMultiError is an error wrapping multiple validation
// errors returned by SendMessageByUserResponse.ValidateAll() if the
// designated constraints aren't met.
type SendMessageByUserResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendMessageByUserResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendMessageByUserResponseMultiError) AllErrors() []error { return m }

// SendMessageByUserResponseValidationError is the validation error returned by
// SendMessageByUserResponse.Validate if the designated constraints aren't met.
type SendMessageByUserResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendMessageByUserResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendMessageByUserResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendMessageByUserResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendMessageByUserResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendMessageByUserResponseValidationError) ErrorName() string {
	return "SendMessageByUserResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SendMessageByUserResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendMessageByUserResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendMessageByUserResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendMessageByUserResponseValidationError{}

// Validate checks the field values on SendMessageByTopicRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SendMessageByTopicRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendMessageByTopicRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SendMessageByTopicRequestMultiError, or nil if none found.
func (m *SendMessageByTopicRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SendMessageByTopicRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetAppName()) < 1 {
		err := SendMessageByTopicRequestValidationError{
			field:  "AppName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Topic

	// no validation rules for Message

	if len(errors) > 0 {
		return SendMessageByTopicRequestMultiError(errors)
	}

	return nil
}

// SendMessageByTopicRequestMultiError is an error wrapping multiple validation
// errors returned by SendMessageByTopicRequest.ValidateAll() if the
// designated constraints aren't met.
type SendMessageByTopicRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendMessageByTopicRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendMessageByTopicRequestMultiError) AllErrors() []error { return m }

// SendMessageByTopicRequestValidationError is the validation error returned by
// SendMessageByTopicRequest.Validate if the designated constraints aren't met.
type SendMessageByTopicRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendMessageByTopicRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendMessageByTopicRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendMessageByTopicRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendMessageByTopicRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendMessageByTopicRequestValidationError) ErrorName() string {
	return "SendMessageByTopicRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SendMessageByTopicRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendMessageByTopicRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendMessageByTopicRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendMessageByTopicRequestValidationError{}

// Validate checks the field values on SendMessageByTopicResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SendMessageByTopicResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendMessageByTopicResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SendMessageByTopicResponseMultiError, or nil if none found.
func (m *SendMessageByTopicResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SendMessageByTopicResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return SendMessageByTopicResponseMultiError(errors)
	}

	return nil
}

// SendMessageByTopicResponseMultiError is an error wrapping multiple
// validation errors returned by SendMessageByTopicResponse.ValidateAll() if
// the designated constraints aren't met.
type SendMessageByTopicResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendMessageByTopicResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendMessageByTopicResponseMultiError) AllErrors() []error { return m }

// SendMessageByTopicResponseValidationError is the validation error returned
// by SendMessageByTopicResponse.Validate if the designated constraints aren't met.
type SendMessageByTopicResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendMessageByTopicResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendMessageByTopicResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendMessageByTopicResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendMessageByTopicResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendMessageByTopicResponseValidationError) ErrorName() string {
	return "SendMessageByTopicResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SendMessageByTopicResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendMessageByTopicResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendMessageByTopicResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendMessageByTopicResponseValidationError{}

// Validate checks the field values on CloseRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CloseRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CloseRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CloseRequestMultiError, or
// nil if none found.
func (m *CloseRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CloseRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ConnId

	if len(errors) > 0 {
		return CloseRequestMultiError(errors)
	}

	return nil
}

// CloseRequestMultiError is an error wrapping multiple validation errors
// returned by CloseRequest.ValidateAll() if the designated constraints aren't met.
type CloseRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CloseRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CloseRequestMultiError) AllErrors() []error { return m }

// CloseRequestValidationError is the validation error returned by
// CloseRequest.Validate if the designated constraints aren't met.
type CloseRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CloseRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CloseRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CloseRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CloseRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CloseRequestValidationError) ErrorName() string { return "CloseRequestValidationError" }

// Error satisfies the builtin error interface
func (e CloseRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCloseRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CloseRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CloseRequestValidationError{}

// Validate checks the field values on CloseResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CloseResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CloseResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CloseResponseMultiError, or
// nil if none found.
func (m *CloseResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CloseResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return CloseResponseMultiError(errors)
	}

	return nil
}

// CloseResponseMultiError is an error wrapping multiple validation errors
// returned by CloseResponse.ValidateAll() if the designated constraints
// aren't met.
type CloseResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CloseResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CloseResponseMultiError) AllErrors() []error { return m }

// CloseResponseValidationError is the validation error returned by
// CloseResponse.Validate if the designated constraints aren't met.
type CloseResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CloseResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CloseResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CloseResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CloseResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CloseResponseValidationError) ErrorName() string { return "CloseResponseValidationError" }

// Error satisfies the builtin error interface
func (e CloseResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCloseResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CloseResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CloseResponseValidationError{}

// Validate checks the field values on GetUserStateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUserStateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserStateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserStateRequestMultiError, or nil if none found.
func (m *GetUserStateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserStateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetAppName()) < 1 {
		err := GetUserStateRequestValidationError{
			field:  "AppName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Topic

	// no validation rules for UserId

	if len(errors) > 0 {
		return GetUserStateRequestMultiError(errors)
	}

	return nil
}

// GetUserStateRequestMultiError is an error wrapping multiple validation
// errors returned by GetUserStateRequest.ValidateAll() if the designated
// constraints aren't met.
type GetUserStateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserStateRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserStateRequestMultiError) AllErrors() []error { return m }

// GetUserStateRequestValidationError is the validation error returned by
// GetUserStateRequest.Validate if the designated constraints aren't met.
type GetUserStateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserStateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserStateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserStateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserStateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserStateRequestValidationError) ErrorName() string {
	return "GetUserStateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserStateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserStateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserStateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserStateRequestValidationError{}

// Validate checks the field values on GetUserStateResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUserStateResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserStateResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserStateResponseMultiError, or nil if none found.
func (m *GetUserStateResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserStateResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ConnId

	// no validation rules for Closed

	// no validation rules for Node

	// no validation rules for ConnectTime

	// no validation rules for DisconnectTime

	if len(errors) > 0 {
		return GetUserStateResponseMultiError(errors)
	}

	return nil
}

// GetUserStateResponseMultiError is an error wrapping multiple validation
// errors returned by GetUserStateResponse.ValidateAll() if the designated
// constraints aren't met.
type GetUserStateResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserStateResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserStateResponseMultiError) AllErrors() []error { return m }

// GetUserStateResponseValidationError is the validation error returned by
// GetUserStateResponse.Validate if the designated constraints aren't met.
type GetUserStateResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserStateResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserStateResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserStateResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserStateResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserStateResponseValidationError) ErrorName() string {
	return "GetUserStateResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserStateResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserStateResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserStateResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserStateResponseValidationError{}

// Validate checks the field values on GetOnlineUsersRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetOnlineUsersRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetOnlineUsersRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetOnlineUsersRequestMultiError, or nil if none found.
func (m *GetOnlineUsersRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetOnlineUsersRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetAppName()) < 1 {
		err := GetOnlineUsersRequestValidationError{
			field:  "AppName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Topic

	// no validation rules for Page

	// no validation rules for PageSize

	if len(errors) > 0 {
		return GetOnlineUsersRequestMultiError(errors)
	}

	return nil
}

// GetOnlineUsersRequestMultiError is an error wrapping multiple validation
// errors returned by GetOnlineUsersRequest.ValidateAll() if the designated
// constraints aren't met.
type GetOnlineUsersRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetOnlineUsersRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetOnlineUsersRequestMultiError) AllErrors() []error { return m }

// GetOnlineUsersRequestValidationError is the validation error returned by
// GetOnlineUsersRequest.Validate if the designated constraints aren't met.
type GetOnlineUsersRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetOnlineUsersRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetOnlineUsersRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetOnlineUsersRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetOnlineUsersRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetOnlineUsersRequestValidationError) ErrorName() string {
	return "GetOnlineUsersRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetOnlineUsersRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetOnlineUsersRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetOnlineUsersRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetOnlineUsersRequestValidationError{}

// Validate checks the field values on GetOnlineUsersResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetOnlineUsersResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetOnlineUsersResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetOnlineUsersResponseMultiError, or nil if none found.
func (m *GetOnlineUsersResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetOnlineUsersResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Count

	if len(errors) > 0 {
		return GetOnlineUsersResponseMultiError(errors)
	}

	return nil
}

// GetOnlineUsersResponseMultiError is an error wrapping multiple validation
// errors returned by GetOnlineUsersResponse.ValidateAll() if the designated
// constraints aren't met.
type GetOnlineUsersResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetOnlineUsersResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetOnlineUsersResponseMultiError) AllErrors() []error { return m }

// GetOnlineUsersResponseValidationError is the validation error returned by
// GetOnlineUsersResponse.Validate if the designated constraints aren't met.
type GetOnlineUsersResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetOnlineUsersResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetOnlineUsersResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetOnlineUsersResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetOnlineUsersResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetOnlineUsersResponseValidationError) ErrorName() string {
	return "GetOnlineUsersResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetOnlineUsersResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetOnlineUsersResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetOnlineUsersResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetOnlineUsersResponseValidationError{}
