// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: longcom.proto

package protocols

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// LongComService defines service.
type LongComService interface {
	// GetToken 获取长连接token, 业务调用
	GetToken(ctx context.Context, req *GetTokenRequest) (*GetTokenResponse, error)
	// Connect 建立长链接, C端网关调用
	Connect(ctx context.Context, req *ConnectRequest) (*ConnectResponse, error)
	// SendMessage 发送长连接消息, 内部自调用
	SendMessage(ctx context.Context, req *SendMessageRequest) (*SendMessageResponse, error)
	// SendMessageByUser 给用户的所有连接发送消息, 业务调用
	SendMessageByUser(ctx context.Context, req *SendMessageByUserRequest) (*SendMessageByUserResponse, error)
	// SendMessageByTopic 给Topic的所有用户连接发送消息, 业务调用
	SendMessageByTopic(ctx context.Context, req *SendMessageByTopicRequest) (*SendMessageByTopicResponse, error)
	// GetUserState 查询用户当前连接状态, 业务调用
	GetUserState(ctx context.Context, req *GetUserStateRequest) (*GetUserStateResponse, error)
	// GetOnlineUsers 获取用户在线列表及在线总数, 业务调用
	GetOnlineUsers(ctx context.Context, req *GetOnlineUsersRequest) (*GetOnlineUsersResponse, error)
}

func LongComService_GetToken_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetTokenRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(LongComService).GetToken(ctx, reqbody.(*GetTokenRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func LongComService_Connect_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ConnectRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(LongComService).Connect(ctx, reqbody.(*ConnectRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func LongComService_SendMessage_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &SendMessageRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(LongComService).SendMessage(ctx, reqbody.(*SendMessageRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func LongComService_SendMessageByUser_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &SendMessageByUserRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(LongComService).SendMessageByUser(ctx, reqbody.(*SendMessageByUserRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func LongComService_SendMessageByTopic_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &SendMessageByTopicRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(LongComService).SendMessageByTopic(ctx, reqbody.(*SendMessageByTopicRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func LongComService_GetUserState_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetUserStateRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(LongComService).GetUserState(ctx, reqbody.(*GetUserStateRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func LongComService_GetOnlineUsers_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetOnlineUsersRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(LongComService).GetOnlineUsers(ctx, reqbody.(*GetOnlineUsersRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// LongComServer_ServiceDesc descriptor for server.RegisterService.
var LongComServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.svip.longcom.LongCom",
	HandlerType: ((*LongComService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.svip.longcom.LongCom/GetToken",
			Func: LongComService_GetToken_Handler,
		},
		{
			Name: "/trpc.svip.longcom.LongCom/Connect",
			Func: LongComService_Connect_Handler,
		},
		{
			Name: "/trpc.svip.longcom.LongCom/SendMessage",
			Func: LongComService_SendMessage_Handler,
		},
		{
			Name: "/trpc.svip.longcom.LongCom/SendMessageByUser",
			Func: LongComService_SendMessageByUser_Handler,
		},
		{
			Name: "/trpc.svip.longcom.LongCom/SendMessageByTopic",
			Func: LongComService_SendMessageByTopic_Handler,
		},
		{
			Name: "/trpc.svip.longcom.LongCom/GetUserState",
			Func: LongComService_GetUserState_Handler,
		},
		{
			Name: "/trpc.svip.longcom.LongCom/GetOnlineUsers",
			Func: LongComService_GetOnlineUsers_Handler,
		},
	},
}

// RegisterLongComService registers service.
func RegisterLongComService(s server.Service, svr LongComService) {
	if err := s.Register(&LongComServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("LongCom register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedLongCom struct{}

// GetToken 获取长连接token, 业务调用
func (s *UnimplementedLongCom) GetToken(ctx context.Context, req *GetTokenRequest) (*GetTokenResponse, error) {
	return nil, errors.New("rpc GetToken of service LongCom is not implemented")
}

// Connect 建立长链接, C端网关调用
func (s *UnimplementedLongCom) Connect(ctx context.Context, req *ConnectRequest) (*ConnectResponse, error) {
	return nil, errors.New("rpc Connect of service LongCom is not implemented")
}

// SendMessage 发送长连接消息, 内部自调用
func (s *UnimplementedLongCom) SendMessage(ctx context.Context, req *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, errors.New("rpc SendMessage of service LongCom is not implemented")
}

// SendMessageByUser 给用户的所有连接发送消息, 业务调用
func (s *UnimplementedLongCom) SendMessageByUser(ctx context.Context, req *SendMessageByUserRequest) (*SendMessageByUserResponse, error) {
	return nil, errors.New("rpc SendMessageByUser of service LongCom is not implemented")
}

// SendMessageByTopic 给Topic的所有用户连接发送消息, 业务调用
func (s *UnimplementedLongCom) SendMessageByTopic(ctx context.Context, req *SendMessageByTopicRequest) (*SendMessageByTopicResponse, error) {
	return nil, errors.New("rpc SendMessageByTopic of service LongCom is not implemented")
}

// GetUserState 查询用户当前连接状态, 业务调用
func (s *UnimplementedLongCom) GetUserState(ctx context.Context, req *GetUserStateRequest) (*GetUserStateResponse, error) {
	return nil, errors.New("rpc GetUserState of service LongCom is not implemented")
}

// GetOnlineUsers 获取用户在线列表及在线总数, 业务调用
func (s *UnimplementedLongCom) GetOnlineUsers(ctx context.Context, req *GetOnlineUsersRequest) (*GetOnlineUsersResponse, error) {
	return nil, errors.New("rpc GetOnlineUsers of service LongCom is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// LongComClientProxy defines service client proxy
type LongComClientProxy interface {
	// GetToken 获取长连接token, 业务调用
	GetToken(ctx context.Context, req *GetTokenRequest, opts ...client.Option) (rsp *GetTokenResponse, err error)
	// Connect 建立长链接, C端网关调用
	Connect(ctx context.Context, req *ConnectRequest, opts ...client.Option) (rsp *ConnectResponse, err error)
	// SendMessage 发送长连接消息, 内部自调用
	SendMessage(ctx context.Context, req *SendMessageRequest, opts ...client.Option) (rsp *SendMessageResponse, err error)
	// SendMessageByUser 给用户的所有连接发送消息, 业务调用
	SendMessageByUser(ctx context.Context, req *SendMessageByUserRequest, opts ...client.Option) (rsp *SendMessageByUserResponse, err error)
	// SendMessageByTopic 给Topic的所有用户连接发送消息, 业务调用
	SendMessageByTopic(ctx context.Context, req *SendMessageByTopicRequest, opts ...client.Option) (rsp *SendMessageByTopicResponse, err error)
	// GetUserState 查询用户当前连接状态, 业务调用
	GetUserState(ctx context.Context, req *GetUserStateRequest, opts ...client.Option) (rsp *GetUserStateResponse, err error)
	// GetOnlineUsers 获取用户在线列表及在线总数, 业务调用
	GetOnlineUsers(ctx context.Context, req *GetOnlineUsersRequest, opts ...client.Option) (rsp *GetOnlineUsersResponse, err error)
}

type LongComClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewLongComClientProxy = func(opts ...client.Option) LongComClientProxy {
	return &LongComClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *LongComClientProxyImpl) GetToken(ctx context.Context, req *GetTokenRequest, opts ...client.Option) (*GetTokenResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.svip.longcom.LongCom/GetToken")
	msg.WithCalleeServiceName(LongComServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("svip")
	msg.WithCalleeServer("longcom")
	msg.WithCalleeService("LongCom")
	msg.WithCalleeMethod("GetToken")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetTokenResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *LongComClientProxyImpl) Connect(ctx context.Context, req *ConnectRequest, opts ...client.Option) (*ConnectResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.svip.longcom.LongCom/Connect")
	msg.WithCalleeServiceName(LongComServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("svip")
	msg.WithCalleeServer("longcom")
	msg.WithCalleeService("LongCom")
	msg.WithCalleeMethod("Connect")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ConnectResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *LongComClientProxyImpl) SendMessage(ctx context.Context, req *SendMessageRequest, opts ...client.Option) (*SendMessageResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.svip.longcom.LongCom/SendMessage")
	msg.WithCalleeServiceName(LongComServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("svip")
	msg.WithCalleeServer("longcom")
	msg.WithCalleeService("LongCom")
	msg.WithCalleeMethod("SendMessage")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &SendMessageResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *LongComClientProxyImpl) SendMessageByUser(ctx context.Context, req *SendMessageByUserRequest, opts ...client.Option) (*SendMessageByUserResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.svip.longcom.LongCom/SendMessageByUser")
	msg.WithCalleeServiceName(LongComServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("svip")
	msg.WithCalleeServer("longcom")
	msg.WithCalleeService("LongCom")
	msg.WithCalleeMethod("SendMessageByUser")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &SendMessageByUserResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *LongComClientProxyImpl) SendMessageByTopic(ctx context.Context, req *SendMessageByTopicRequest, opts ...client.Option) (*SendMessageByTopicResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.svip.longcom.LongCom/SendMessageByTopic")
	msg.WithCalleeServiceName(LongComServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("svip")
	msg.WithCalleeServer("longcom")
	msg.WithCalleeService("LongCom")
	msg.WithCalleeMethod("SendMessageByTopic")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &SendMessageByTopicResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *LongComClientProxyImpl) GetUserState(ctx context.Context, req *GetUserStateRequest, opts ...client.Option) (*GetUserStateResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.svip.longcom.LongCom/GetUserState")
	msg.WithCalleeServiceName(LongComServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("svip")
	msg.WithCalleeServer("longcom")
	msg.WithCalleeService("LongCom")
	msg.WithCalleeMethod("GetUserState")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetUserStateResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *LongComClientProxyImpl) GetOnlineUsers(ctx context.Context, req *GetOnlineUsersRequest, opts ...client.Option) (*GetOnlineUsersResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.svip.longcom.LongCom/GetOnlineUsers")
	msg.WithCalleeServiceName(LongComServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("svip")
	msg.WithCalleeServer("longcom")
	msg.WithCalleeService("LongCom")
	msg.WithCalleeMethod("GetOnlineUsers")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetOnlineUsersResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
